name: bmi_calculator
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2

  

  font_awesome_flutter: ^10.2.1
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo1.png"


  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "BMI Calculator"
  
  
  
  
  flutter_lints: ^1.0.0
 


flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - images/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
